[package]
name = "recipes"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"]}
serde_yaml = "0.9"
handlebars = { version = "4.3.4", features = ["dir_source"]}
